default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  host: localhost
  password:

production:
  <<: *default
  database: weishop_origin
  username: root
  password: <%= ENV['WEISHIOP_DATABASE_PASSWORD'] %>
